### ISSUE TITLE
Error while installing the library

### ISSUE THREAD

**Issue by rtmlp** [itslenny/slack-emoji-import#2]
Hi,

Thanks for creating and sharing the repo

While trying to install, I got the following errors

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.9.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rmulpuri/.npm/_logs/2018-10-09T16_17_28_069Z-debug.log
```

Not sure how to go about it.

Thanks

**Comment by breadbored** [comment]
I know this is a year late, but I assume you're on macOS?

For other's reference: You need to clone the GitHub repo, `cd` into the folder, and `npm install`

Once you do that, use `node index.ts file.yaml` from inside that folder instead of `slack-emoji-import
 file.yaml`
